### ISSUE TITLE
pip._vendor.pep517.wrappers.BackendUnavailable

### ISSUE THREAD

**Issue by jhgoebbert** [takluyver/bash_kernel#100]
Hi takluyver,

thank you for the bash kernel.

Unfortunately we cannot install version 0.7.2 because of the installation error "pip._vendor.pep517.wrappers.BackendUnavailable" which seems to be an issue with PEP517
https://pip.pypa.io/en/stable/reference/pip/?highlight=no-use-pep517#pep-517-and-518-support

Best regards,
Jens Henrik

**Comment by kdm9** [comment]
This issue seems fixed at least on every system I've tried recently, so closing as stale. If the problem persists, feel free to reopen.
