### ISSUE TITLE
can't read input

### ISSUE THREAD

**Issue by d2jvkpn** [takluyver/bash_kernel#106]
enter and execute "read input" in cell, no way to type text

**Comment by bitdivine** [comment]
Here is a related issue in jupyter lab.  It seems that jupyter has a standard pop-up for getting user input.  Presumably the bash kernel needs a way of invoking that pop-up.  https://github.com/jupyterlab/jupyterlab/issues/8522

**Comment by d2jvkpn** [comment]
Thank you!

**Comment by chaosdinosaur** [comment]
I wonder if something like what the [.NET Interactive](https://github.com/dotnet/interactive) kernel does for `Read-Host` could be created for this kernel?
