### ISSUE TITLE
`[?2004l` characters when outputing 

### ISSUE THREAD

**Issue by moneroexamples** [takluyver/bash_kernel#107]
I encountered strange issue which prohibits cells from running in sequence as numerical outputs were postfixes with `[?2004l` or `[?200hl`:

![image](https://user-images.githubusercontent.com/15305358/107108918-ce35e400-6876-11eb-99cc-b52c11d257d4.png)

Found that setting 

```
bind 'set enable-bracketed-paste off'
```

in first cell fixes the issue:

![image](https://user-images.githubusercontent.com/15305358/107108935-f4f41a80-6876-11eb-9075-84b3a20c18c1.png)

**Comment by hcz** [comment]
> Found that setting fixes the issue
> 
> `bind 'set enable-bracketed-paste off'`

Thanks, @moneroexamples!

**Comment by takluyver** [comment]
I think #120 should fix this.
