### ISSUE TITLE
Get output of the last command

### ISSUE THREAD

**Issue by bitdivine** [takluyver/bash_kernel#108]
Greetings, thank you for this kernel.

Is there a way of getting the stdout of a previous command?  I see that `Out` is [defined as an array in iPython](https://jakevdp.github.io/PythonDataScienceHandbook/01.04-input-output-history.html).  bash isn't quite as array friendly; perhaps a shell command to get the output N steps ago would be more idiomatic for bash.  What do you think?

**Comment by takluyver** [comment]
There isn't. Unless there are some bash features I don't know about, it would be more complicated for bash_kernel, where the process running your code is separate from the kernel machinery, than for IPython, where they both happen in the same process. Not impossible, just more complicated.

**Comment by bitdivine** [comment]
Thank you.  I saw the "export as bash" option.  I imagine that would also be complicated by such a feature.  At the moment I am using `somevar="$(somecommand)" ; echo "$somevar"` .  I guess I could make that more interactive with `| tee /dev/stderr`, so that I see the output as it comes rather than having to wait for the command to finish.  Either way this is a simple enough alternative.
