### ISSUE TITLE
Why step `python -m bash_kernel.install` cannot be inside the usual pypi package?

### ISSUE THREAD

**Issue by alanwilter** [takluyver/bash_kernel#110]
I'm wondering why, after `pip install bash-kernel`, one still need to do:
```
python -m bash_kernel.install
```
I've found the hard way that `bash-kernel` won't work with python venv if this step is not done.

**Comment by kdm9** [comment]
see https://stackoverflow.com/questions/76320274/post-install-script-for-pyproject-toml-projects and linked questions/docs for a discussion of why this is not possible
