### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by enzotib** [takluyver/bash_kernel#112]
I installed to try, but I would like to uninstall.
Uninstalling bash_kernel with pip is not enough

**Comment by arogozhnikov** [comment]
https://github.com/takluyver/bash_kernel/issues/13#issuecomment-527510754

solved the issue for me

**Comment by kdm9** [comment]
I've recently taken on co-maintaining `bash_kernel`, and I'm currently closing all old/stale issues.

I'm closing this issue as a duplicate of #13. Please reopen if you need further help.
