### ISSUE TITLE
Doesn't seem to work with VS Code Jupyter integration

### ISSUE THREAD

**Issue by Pawper** [takluyver/bash_kernel#114]
Any help appreciated!

I'm using VS Code Insiders on Windows. I have WSL2 set up and I'm remotely in WSL Ubuntu-20.04 via VS Code. 

Python 3.8.10
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : 5.1.1
ipython          : 7.26.0
ipykernel        : 6.0.3
jupyter client   : 6.1.12
jupyter lab      : not installed
nbconvert        : 6.1.0
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5

Neither of these cells output when I click the run button:
![image](https://user-images.githubusercontent.com/22269691/127956894-a2d9e27c-2224-41ff-b2ec-1a71a28fc1a2.png)

**Comment by kdm9** [comment]
So a colleage here has been using VS code's jupyter interaction to use this kernel recently, and apparently it works fine for them. @Pawper does this issue persist for you? If not, please close this. If it's still broken, please provide a few more details of your setup, including trying this kernel in the normal jupyter interface

**Comment by kdm9** [comment]
closing due to lack of response, but if anyone has a similar issue please reopen
