### ISSUE TITLE
Running any cell (containing any shell command or function definition) always produces non-zero exit status (+workaround)

### ISSUE THREAD

**Issue by ackalker** [takluyver/bash_kernel#117]
When I run any cell with Bash code in it with Bash kernel, it always returns a non-zero exit status.
The issue seems to be related to both issues #116, #115 and #107 as the workaround mentioned in those issues works for this one as well, but I haven't seen any garbled output so far.

In order to not have to include `bind 'set enable-bracketed-paste off'` at the beginning of each and every notebook using the Bash kernel, I've added the following kludgy hack to my `~/.bashrc` for now:

`[[ $(< /proc/$PPID/comm) == python* ]] && bind 'set enable-bracketed-paste off'`

This should apply the workaround to any interactive Bash shell running as a child process of a Python process (assuming that process to be the Bash kernel in most cases), and not to any other interactive shell.

@takluyver Is there a better way to detect if the shell process is running in the Bash kernel? Any advice is very welcome.

**Comment by takluyver** [comment]
0.8 should fix this (thanks to PR #120).

As a separate matter, I'm still open to setting some environment variable to indicate that it's bash_kernel outside the terminal. I'm a bit puzzled about TERM vs TERM_PROGRAM - my modern Linux system still doesn't seem to set TERM_PROGRAM automatically or use it, so I don't know if that's mostly an Apple thing or just randomly hasn't reached Fedora yet. :shrug:
