### ISSUE TITLE
Need to bump version & update PyPI to pick up fix for #8

### ISSUE THREAD

**Issue by payne92** [takluyver/bash_kernel#12]
The version of bash_kernel on PyPI is dated, see:  https://pypi.python.org/pypi/bash_kernel/0.2

In particular, it's missing the fix to #8, which updates the stdout kernel message to v5 for IPython 3.  Currently, users installing via:

    pip install bash_kernel

will get the older version, which does not work with IPython 3.

**Comment by takluyver** [comment]
Thanks, done.
