### ISSUE TITLE
New pypi release ? 

### ISSUE THREAD

**Issue by janpfeifer** [takluyver/bash_kernel#124]
hi @kdm9 ,

With the new changes, the documentation in README.rst and the package one gets from `pip install bash_kernel` is out-of-sync.

Any thoughts on building a new release ? (0.9.0 ?) -- it's work :( ... but considering the recent changes, it would be nice :)

cheers

**Comment by kdm9** [comment]
Ah yes, of course. I was waiting until I'd tested it more extensively on my own systems and with my own work, and then got engrossed in said work and forgot all about the release. I'll release it now.

**Comment by janpfeifer** [comment]
Cool, thanks. Not urgent, but it would be nice to have :)

**Comment by kdm9** [comment]
@janpfeifer released, tagged, and published to pypi as 0.9.0. Fingers crossed all has worked as this is the first release I've made in this repo. Please let me know if I've screwed anything up :)

**Comment by janpfeifer** [comment]
Thank you! I tested here as well, all worked perfectly.
