### ISSUE TITLE
Disabling non-bash-related tab-auto-complete suggestions in jupyter notebook bash kernel

### ISSUE THREAD

**Issue by AstrobioMike** [takluyver/bash_kernel#127]
Hiya, thanks for developing/maintaining this!

I think this might be more a question for jupyter (and i do have a [post](https://discourse.jupyter.org/t/disabling-tab-auto-complete-suggestions-in-jupyter-notebook-bash-kernel/17819) for it on the jupyter discourse), but I also figured I'd ask here as ultimately I think it'll benefit the bash kernel overall, and I'm hoping maybe i get lucky :)

For various reasons I'm working on putting some of my unix intro lessons into jupyter notebooks. But unfortunately even when in the bash kernel, tab-completion is bringing up more than is relevant due to the inclusion of additional auto-completion suggestions, e.g., as in this image:

![image](https://user-images.githubusercontent.com/13923308/216883036-bfefef6d-6296-4ada-9740-7865d480078b.png)

where all that should pop up is "experiment". This situation basically precludes the ability to use bash tab-completion in a notebook, which is a very sad thing for hopes of teaching it to new-comers. 

Anyone know of a way to disable these non-bash auto-completion suggestions? I can't imagine a scenario where they'd be useful at all in a bash kernel, so in general I think it'd be great if we could somehow deactivate them when a bash kernel is active. 

Thanks for any help/thoughts!

**Comment by kdm9** [comment]
@AstrobioMike see https://github.com/takluyver/bash_kernel/pull/126

Please install from the dev branch, and let me know if it fixes it for you.

**Comment by AstrobioMike** [comment]
Ahhh, of course. I was looking at that, but i had it in my head that these (what i was talking about) were somehow python-related, and not just any possible command or something else from bash. I think i see now i was wrong, ha. Thanks, excited to try that out, will let you know!

**Comment by kdm9** [comment]
Closing this issue as I *think* the situation has improved in 0.9.3 -- reopen if there are further improvements needed
