### ISSUE TITLE
Non-zero errors with bash notebook in VS Code

### ISSUE THREAD

**Issue by davidchatz** [takluyver/bash_kernel#137]
When running a notebook in VS Code its always generating an error with any cell despite it running successfully. I can see similar issues were raised with versions pre 0.8 (#120), but I'm running

bash_kernel 0.9.1
python 3.11
jupyter 6.1.12
jupyter vscode extension v2023.11.1003402403
macosx 13.6.1

```bash
echo "hello world"
```

```
echo "hello world"
hello world

1
```

This kernel and notebooks run just fine when run from jupyter lab, but it would be more convenient if I could run them directly from VS Code.

The kernel spec is
```json
{"argv": ["/usr/local/opt/python@3.11/bin/python3.11", "-m", "bash_kernel", "-f", "{connection_file}"], "codemirror_mode": "shell", "display_name": "Bash", "env": {"PS1": "$"}, "language": "bash"}
```

```bash
echo $PS1
echo $TERM
```

```
echo $PS1
PROMPT_HENTDKWZSIFS\[\]>
echo $TERM
dumb
```

Any suggestions on what to try?

**Comment by kdm9** [comment]
Double check that bash_kernel 0.9.3 has the same bug you're hitting, as #136 could fix strangeness with more non-standard bash configurations.

**Comment by kdm9** [comment]
closing this due to lack of response, but please reopen if problems persist
