### ISSUE TITLE
Add instructions for installation with pipx

### ISSUE THREAD

**Issue by knh11545** [takluyver/bash_kernel#138]
# Issue

[PEP 668 - Marking Python base environments as “externally managed”](https://peps.python.org/pep-0668/#guide-users-towards-virtual-environments) recommends that users install Python applications with `pipx`. This is strongly suggested/enforced in current Linux distros.

`bash_kernel` needs an extra step to actually work after installing with `pip` or `pipx` (See also #110):

```bash
python -m bash_kernel.install
```
I found doing that additional step after `jupyter` was installed with `pipx` was not straightforward. I found no documentation.

# My workaround

The following worked for me (Debian 12):

```bash 
pipx install --include-deps jupyter
pipx inject --include-apps --include-deps jupyter bash_kernel
```

`pipx` installs packages into their own virtual environment. 

Find the path of the venv where `jupyter` was installed with `pipx list`. Here it is `~/.local/pipx/venvs`. Then go to the `jupyter` venv directory and complete the installation:

```bash 
cd ~/.local/pipx/venvs/jupyter/
source bin/activate
python -m bash_kernel.install
deactivate
```

# Suggestion

Add instructions for installation of `bash_kernel` with `pipx`.

Better still would probably be to avoid having to do this extra manual step during installation.

**Comment by kdm9** [comment]
many thanks for this suggestion, which I've finally gotten around to doing :)
