### ISSUE TITLE
AttributeError: no 'signal.SIGPIPE' module.attribute

### ISSUE THREAD

**Issue by goyalyashpal** [takluyver/bash_kernel#143]
### summary

```console
> jupyter console --kernel bash
```

```python
AttributeError: module 'signal' has no attribute 'SIGPIPE'. Did you mean: 'SIGFPE'?
```

### duplicates

[powershell_kernel]: https://github.com/vors/jupyter-powershell

yes i have seen these older issues. but at least 5 years have passed since:
* windows have gotten the `pty` support, and 
* scope of this issue has become much smaller
    -- whole module `pexpect` not found 
    -> `pexpect.spawn` not found 
    -> `signal.SIGPIPE` constant literal not found
* <tt>[powershell_kernel]</tt> says that's based on this, and yet that works fine on windows 😃 

and it seems that it finally just _might_ start to work properly on windows too :)

* 2017.06 or 2019.02 or 2019.05: no `pexpect.spawn`
https://github.com/takluyver/bash_kernel/issues/62
https://github.com/takluyver/bash_kernel/issues/84
https://github.com/takluyver/bash_kernel/issues/96

* 2015.09: no `pexpect` module on windows  
no `pty` on windows
https://github.com/takluyver/bash_kernel/issues/34

### full traceback

<details>
<summary>
<p>

```console
> .\.venv\Scripts\Activate.ps1

(.venv)
> which pip; which python
.../.venv/Scripts/pip
.../.venv/Scripts/python

(.venv)
> python -m bash_kernel.install
Installing IPython kernel spec

(.venv)
> jupyter console --kernel bash
... Click me for full traceback ...
```

</summary>

```log
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "...\site-packages\bash_kernel\__main__.py", line 3, in <module>
    IPKernelApp.launch_instance(kernel_class=BashKernel)
  File "...\site-packages\traitlets\config\application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "...\site-packages\traitlets\config\application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\site-packages\ipykernel\kernelapp.py", line 707, in initialize
    self.init_kernel()
  File "...\site-packages\ipykernel\kernelapp.py", line 555, in init_kernel
    kernel = kernel_factory(
             ^^^^^^^^^^^^^^^
  File "...\site-packages\traitlets\config\configurable.py", line 583, in instance
    inst = cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "...\site-packages\bash_kernel\kernel.py", line 104, in __init__
    self._start_bash()
  File "...\site-packages\bash_kernel\kernel.py", line 116, in _start_bash
    old_sigpipe_handler = signal.signal(signal.SIGPIPE, signal.SIG_DFL)
                                        ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGPIPE'. Did you mean: 'SIGFPE'?
```

</p>
</details> 

### versions

```console
> pip list | grep -E "(powershell|bash)_kernel"
bash_kernel               0.9.3
powershell_kernel         0.1.4

> python --version
Python 3.12.2

> systeminfo | grep -Ei "^os name|system type"
OS Name:                   Microsoft Windows 10 Home Single Language
System Type:               x64-based PC
```

**Comment by kdm9** [comment]
@goyalyashpal please try to install bash_kernel from this PR: https://github.com/takluyver/bash_kernel/pull/144 (instructions there)

**Comment by goyalyashpal** [comment]
i think the issue of `readline` not found in some other modules is also related to this `pexpect.spawn` not found
* https://github.com/cs50/submit50/issues/173

**Comment by guquandaju012** [comment]
Same problem found on windows 10, any solution to this problem? Thanks a lot.

**Comment by goyalyashpal** [comment]
> Same problem found on windows 10, any solution to this problem? Thanks a lot.

i replaced my older **_boot drive_** with a brand new one and installed linux on it.
