### ISSUE TITLE
ImportError: No module named kernelspec

### ISSUE THREAD

**Issue by BurtonChia** [takluyver/bash_kernel#18]
Hi, I'm trying to install the bash_kernel on my local machine and I'm getting this error message:

chiakhb@localhost bash_kernel-master]$ sudo python setup.py install
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /usr/lib/python2.7/site-packages/bash_kernel-0.3-py2.7.egg-info
Writing /usr/lib/python2.7/site-packages/bash_kernel-0.3-py2.7.egg-info
Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    'Topic :: System :: Shells',
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 21, in run
    from IPython.kernel.kernelspec import install_kernel_spec
ImportError: No module named kernelspec

**Comment by takluyver** [comment]
I suspect you have an older version of IPython. You will need version 3 to
use bash_kernel.

**Comment by BurtonChia** [comment]
Hi. IPython is currently at version 3.

[chiakhb@localhost bash_kernel]$ ipython
Python 2.7.9 |Anaconda 2.1.0 (64-bit)| (default, Dec 15 2014, 10:33:51) 
Type "copyright", "credits" or "license" for more information.

IPython 3.0.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: exit
[chiakhb@localhost bash_kernel]$ sudo python setup.py install
[sudo] password for chiakhb: 
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /usr/lib/python2.7/site-packages/bash_kernel-0.3-py2.7.egg-info
Writing /usr/lib/python2.7/site-packages/bash_kernel-0.3-py2.7.egg-info
Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    'Topic :: System :: Shells',
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 21, in run
    from IPython.kernel.kernelspec import install_kernel_spec
ImportError: No module named kernelspec
[chiakhb@localhost bash_kernel]$

**Comment by takluyver** [comment]
'sudo python' may be seeing a different python installation with an older
version of IPython. That module is definitely there in ipython 3.

**Comment by BurtonChia** [comment]
Hi. I fixed the issue. You're right...sudo ipython gives an older ipython v2 even though ipython 3 was installed for root.
