### ISSUE TITLE
Python module pexpect is required for installation 

### ISSUE THREAD

**Issue by drtamermansour** [takluyver/bash_kernel#20]
Otherwise they kernel will die overtime you try to start a new bash file
the module can be found at
https://github.com/pexpect/pexpect

**Comment by crazyhottommy** [comment]
yes, I also found this. after installing pexpect, it is working now.

**Comment by takluyver** [comment]
If you `pip install bash_kernel`, it should pull in pexpect automatically.

**Comment by takluyver** [comment]
Ah, I see, the README still mentions setup.py. I'll fix that.
