### ISSUE TITLE
%load and %run Not Working

### ISSUE THREAD

**Issue by joshlatto** [takluyver/bash_kernel#21]
When I try:

%run TEST_Bash_Script.sh 

it returns:

bash: fg: %run: no such job

I'm not sure if the %run and %load cell magic is supposed to be available with the bash_kernel, but even if it isn't, it would be very nice to have. Thanks!

**Comment by takluyver** [comment]
They're not supposed to be available. You can use standard bash commands like `source myscript.sh` or `. myscript.sh` for `%run` (or just `./myscript.sh` if you don't need the variables). There's not currently anything like %load.

**Comment by joshlatto** [comment]
Thank you!
