### ISSUE TITLE
Multi-line echo only displays last echo

### ISSUE THREAD

**Issue by rgbkrk** [takluyver/bash_kernel#24]
Within a notebook,

```
echo "hi"
echo "wat"
```

will only display "wat". Is this the intended behavior?

**Comment by takluyver** [comment]
It's not. I think I've already fixed it in pexpect, but we haven't got
round to making a release yet.

**Comment by mjbright** [comment]
Any news on this?

For me **bash_kernel is a killer app** on Jupyter ... handy for doing tutorials of command-line stuff ... but not so handy when I have to put all commands on a line separated by semi-colons.

In the above example for example
&nbsp;&nbsp;&nbsp;&nbsp;echo "hi"; echo "wat"
would be a somewhat ugly workaround which detracts from the message ...

**Comment by takluyver** [comment]
Mike, what version of Pexpect are you using? I think this is fixed in Pexpect 4, but if you've installed Anaconda you may still have got Pexpect 3.3. If so:

```
conda uninstall pexpect
pip install pexpect
```

**Comment by mjbright** [comment]
On 31 January 2016 at 19:21, Thomas Kluyver <notifications@github.com>
wrote:

> conda uninstall pexpect
> pip install pexpect
>
>
Hah excellent ... thanks very much, this is now working fine !

**Comment by takluyver** [comment]
Great :-)
