### ISSUE TITLE
Use bash completion for tab completion

### ISSUE THREAD

**Issue by rgbkrk** [takluyver/bash_kernel#26]
If this is possible, awesome.

**Comment by takluyver** [comment]
It should already, and #25 just extended what it can complete. Is there something specific you're thinking of?

**Comment by rgbkrk** [comment]
It was just a bit of a disconnect between what was on try.jupyter.org within the kernel and what I get out of the terminal.

**Comment by takluyver** [comment]
bash_kernel uses bash's machinery (`compgen`), but it doesn't actually send `text+'\t'` to the terminal, because that would be tricky to handle correctly. Closing this for now, feel free to open issues for specific issues you see in tab completion.

**Comment by rgbkrk** [comment]
Ah, ok. Perhaps I'll get to come back to this later. Thanks @takluyver
