### ISSUE TITLE
Installation fails when installing on systems without root access

### ISSUE THREAD

**Issue by BurtonChia** [takluyver/bash_kernel#27]
(ipython3)[chiakhb@n069 CAMI]$ pip install bash_kernel
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting bash-kernel
  Using cached bash_kernel-0.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pexpect>=3.3 in /mnt/software/unstowable/anaconda/envs/ipython3/lib/python2.7/site-packages (from bash-kernel)
Installing collected packages: bash-kernel
  Running setup.py install for bash-kernel
    Installing IPython kernel spec
    error: [Errno 13] Permission denied: '/usr/local/share/jupyter'
    Complete output from command /mnt/software/unstowable/anaconda/envs/ipython3/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-KkZeU0/bash-kernel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-aMy_O4-record/install-record.txt --single-version-externally-managed --compile:
    running install
    
    running build
    
    running build_py
    
    creating build
    
    creating build/lib
    
    creating build/lib/bash_kernel
    
    copying bash_kernel/__init__.py -> build/lib/bash_kernel
    
    copying bash_kernel/images.py -> build/lib/bash_kernel
    
    copying bash_kernel/__main__.py -> build/lib/bash_kernel
    
    copying bash_kernel/kernel.py -> build/lib/bash_kernel
    
    running install_lib
    
    creating /mnt/software/unstowable/anaconda/envs/ipython3/lib/python2.7/site-packages/bash_kernel
    
    copying build/lib/bash_kernel/__init__.py -> /mnt/software/unstowable/anaconda/envs/ipython3/lib/python2.7/site-packages/bash_kernel
    
    copying build/lib/bash_kernel/images.py -> /mnt/software/unstowable/anaconda/envs/ipython3/lib/python2.7/site-packages/bash_kernel
    
    copying build/lib/bash_kernel/__main__.py -> /mnt/software/unstowable/anaconda/envs/ipython3/lib/python2.7/site-packages/bash_kernel
    
    copying build/lib/bash_kernel/kernel.py -> /mnt/software/unstowable/anaconda/envs/ipython3/lib/python2.7/site-packages/bash_kernel
    
    byte-compiling /mnt/software/unstowable/anaconda/envs/ipython3/lib/python2.7/site-packages/bash_kernel/__init__.py to __init__.pyc
    
    byte-compiling /mnt/software/unstowable/anaconda/envs/ipython3/lib/python2.7/site-packages/bash_kernel/images.py to images.pyc
    
    byte-compiling /mnt/software/unstowable/anaconda/envs/ipython3/lib/python2.7/site-packages/bash_kernel/__main__.py to __main__.pyc
    
    byte-compiling /mnt/software/unstowable/anaconda/envs/ipython3/lib/python2.7/site-packages/bash_kernel/kernel.py to kernel.pyc
    
    running install_egg_info
    
    running egg_info
    
    creating bash_kernel.egg-info
    
    writing requirements to bash_kernel.egg-info/requires.txt
    
    writing bash_kernel.egg-info/PKG-INFO
    
    writing top-level names to bash_kernel.egg-info/top_level.txt
    
    writing dependency_links to bash_kernel.egg-info/dependency_links.txt
    
    writing manifest file 'bash_kernel.egg-info/SOURCES.txt'
    
    warning: manifest_maker: standard file '-c' not found
    
    
    
    reading manifest file 'bash_kernel.egg-info/SOURCES.txt'
    
    writing manifest file 'bash_kernel.egg-info/SOURCES.txt'
    
    Copying bash_kernel.egg-info to /mnt/software/unstowable/anaconda/envs/ipython3/lib/python2.7/site-packages/bash_kernel-0.3-py2.7.egg-info
    
    writing list of installed files to '/tmp/pip-aMy_O4-record/install-record.txt'
    
    Installing IPython kernel spec
    
    error: [Errno 13] Permission denied: '/usr/local/share/jupyter'
    
    ----------------------------------------
    Command "/mnt/software/unstowable/anaconda/envs/ipython3/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-KkZeU0/bash-kernel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-aMy_O4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-KkZeU0/bash-kernel

**Comment by lstagner** [comment]
You could always install it in your user directory. 

```pip install --user bash_kernel```

**Comment by gatagat** [comment]
User install is not always possible... However, it seems that the only thing that is missing is a creation of a kernel.json file.

The following did the trick for me:
```
mkdir -p ~/.ipython/kernels/bash 2> /dev/null
cd ~/.ipython/kernels/bash
python -c '
import sys
import json
kernel_json = {
        "argv":[sys.executable,"-m","bash_kernel", "-f", "{connection_file}"],
         "display_name":"Bash",
         "language":"bash",
         "codemirror_mode":"shell",
         "env":{"PS1": "$"}
}
with open("kernel.json", "w") as f:
        json.dump(kernel_json, f, sort_keys=True)
'
```

**Comment by BurtonChia** [comment]
thanks
