### ISSUE TITLE
Error when installing in OSX

### ISSUE THREAD

**Issue by ajmazurie** [takluyver/bash_kernel#29]
Regardless of the method; i.e., using `pip install bash_kernel` or downloading a snapshot from Github and manually launching `python setup.py install` I get the following error:

```
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/bash_kernel
copying bash_kernel/__init__.py -> build/lib/bash_kernel
copying bash_kernel/__main__.py -> build/lib/bash_kernel
copying bash_kernel/images.py -> build/lib/bash_kernel
copying bash_kernel/kernel.py -> build/lib/bash_kernel
running install_lib
running install_egg_info
removing '/Users/ajmazurie/.pyenv/versions/_jupyter/lib/python2.7/site-packages/bash_kernel-0.3-py2.7.egg-info' (and everything under it)
Writing /Users/ajmazurie/.pyenv/versions/_jupyter/lib/python2.7/site-packages/bash_kernel-0.3-py2.7.egg-info
Installing IPython kernel spec
error: [Errno 13] Permission denied: '/usr/local/share/jupyter'
```

It appears that the installation process expects a hardcoded folder `/usr/local/share/jupyter/`, which is not installed by Jupyter (at least not on my Mac). I'm using OSX 10.10.3 and Jupyter 3.2.1

Best,
Aurelien

**Comment by takluyver** [comment]
For the moment, you need to install with `pip install --user bash_kernel`. I think I'm going to make this a two-step setup to avoid this.

**Comment by ajmazurie** [comment]
I confirm that this fix works; unfortunately it breaks virtual environment management toolkits, such as virtualenv and pyenv.

Best, Aurelien

**Comment by takluyver** [comment]
OK, I've done it as a two-step install process now:

    pip install bash_kernel
    python -m bash_kernel.install

**Comment by ajmazurie** [comment]
I realize I never confirmed that your fix worked, but it does. Thanks!
