### ISSUE TITLE
 bash kernel fails to start with :  CRITICAL | Could not find kernel bash 

### ISSUE THREAD

**Issue by shayanrc** [takluyver/bash_kernel#30]
When I run: ipython console --kernel bash

The bash kernel fails to start with:
 CRITICAL | Could not find kernel bash 

The same thing happens when I run the qtconsole

**Comment by takluyver** [comment]
If you installed it recently, you need to do `python -m bash_kernel.install`, as mentioned in the README.

**Comment by shayanrc** [comment]
My bad..
I missed that part.
