### ISSUE TITLE
feature request: use bash_kernel functionality for magics - code supplied

### ISSUE THREAD

**Issue by kbroughton** [takluyver/bash_kernel#32]
I've got a basic pass at persistent bash magics working based on bash_kernel.
Because of singletons, i had to make
BashKernel(object) and __init__(self, kernel, **kwargs)

Is there a better way to share the code of bash_kernel/kernel.py for these two purposes?

See gist for details.
https://gist.github.com/kbroughton/e82a9e381cdf228eb380

**Comment by takluyver** [comment]
Hi @kbroughton , sorry for the long delay in responding to this (I'm just trawling through old emails).

I'm not sure that there's much advantage to using the bash_kernel machinery here. bash_kernel itself is a wrapper around Pexpect's [replwrap module](http://pexpect.readthedocs.org/en/stable/api/replwrap.html). I think you could reuse replwrap for a stateful bash magic without much code duplication from bash_kernel.

**Comment by steffenheyne** [comment]
More a general comment: 
I'm working in a Bioinformatics context and we started using ipython/jupyter with various kernels like python, R, perl and also this bash kernel. This is all working very well and is really useful. Thanks for this bash kernel!

In Bioinformatics, analyses often consist of small workflows/"pipelines" that incorporate various tools or languages.  If the bash kernel would have similar magic commands like the python kernel, this would really be the "killer" feature/tool for us as then a single notebook could be used for an entire analysis. Currently, we start with bash, then have another R or Python notebook to execute some plot function and then go back to the bash notebook to to do the next step and so on...magic commands could help here a lot by just calling something in R or Python within a cell and then continue with the result in bash...

From my perspective I have no glue how I have to code a kernel or even this magic commands, but I/we would really appreciate to have such a function within the bash kernel.

**Comment by takluyver** [comment]
@steffenheyne that's something distinct from what this issue was asking for (a way to use bash_kernel in a magic for IPython). What you're asking for is #43.

I don't plan to implement magics for bash_kernel. If you want to mix and match languages, I would encourage you to use a Python notebook, and use the `%%bash` and `%%R` magics (the latter is provided by rpy2 - use `%load_ext rpy2.ipython`).

**Comment by steffenheyne** [comment]
ah ok, I didn't got this! Thanks!
Yes, the magics in Python are great and I know how to use them, but this is not the same as if they would be in bash. Bash/shell is the unifying thing in some scenarios, not python.
