### ISSUE TITLE
Typing env "breaks" the kernel

### ISSUE THREAD

**Issue by mjbright** [takluyver/bash_kernel#33]
Running under IPython 4.0.0/Jupyter 4.0.4 if I run env in a cell, that works fine ... but subsequently all bash commands just provide '0' as output and after several commands the output of one cell corresponds to the command of another cell.

Of course, restarting the kernel puts things right again.

Experimenting I found that if I ran
    env | grep -v ^PS1

This avoids the problem.

I don't understand the cause of this problem, but it would be good that the kernel could correct for this (which is presumably one of a class of similar problem?)

**Comment by takluyver** [comment]
It's looking for the prompt to determine where the output from a cell finishes. If something prints out the prompt for some other reason, it will get confused, as you see. It changes the prompt to something unlikely to be printed otherwise, to avoid that issue, but of course `env` will still print the value of `PS1`. I can't currently see a way to avoid that.

**Comment by mjbright** [comment]
Ahem, of course ...
I guess looking for "env" as a command or "echo $PS1" is just too much of a
special case.

On the other hand, is there any way this situation can be detected and to
some extent corrected, to avoid the need for a kernel restart at least?

**Comment by takluyver** [comment]
Nothing springs to mind as yet, but I'll keep thinking about it.

**Comment by andydude** [comment]
It's not a "special case", the first command I tried when experimenting was "env | sort" and I didn't understand why nothing worked afterwords, it made me believe that the Bash kernel was not functional. If someone has a very simple prompt, like "/" for example, then won't this make any path-printing command cause the kernel to hang like this? This is a fundamental design flaw, indicating poor software engineering choices, not a "special case".

**Comment by takluyver** [comment]
When it starts bash, the prompt is changed to something that's unlikely to come up in other contexts, so it's independent of what prompt you normally have in bash.

I haven't thought of a way to set the prompt without the output of `env` or `echo $PS1` containing the same string. Though now that I come back to it, maybe we can do some trick with PROMPT_COMMAND.

**Comment by Honestpuck** [comment]
What about the possibility of having PS1 blank and having PROMPT_COMMAND as something like "echo `id -u`" so that the shell issues something that can be searched for that is not the contents of any actual shell variable.

Of course if PROMPT_COMMAND is already defined the above would have to be affixed to the end of the existing one.

**Comment by takluyver** [comment]
I found a neater way, by embedding characters in PS1 which are invisible when the prompt is displayed. See pexpect/pexpect#362.

**Comment by nbrunett** [comment]
What is PS1 actually set to? Is it `[PEXP\[\]ECT_PROMPT>` ? I have a Bash file I source occasionally to setup my environment for running an astronomy package called Starlink. I have set this up to change my prompt which the notebook does not like. I want to add an if statement to check when the prompt is set to whatever Jupyter sets it to so I can skip changing the prompt. What should my if statement check PS1 for? Thank you.

**Comment by takluyver** [comment]
Yes, PS1 should be set to `[PEXP\[\]ECT_PROMPT>`. However, it's an implementation detail, so it's not ideal to rely on that for checking 'is this bash_kernel'. I've opened #54 for that. In the meantime, I think checking if `JPY_PARENT_PID` is set should be a good indicator that it's running in Jupyter.
