### ISSUE TITLE
Support for Cygwin on Windows

### ISSUE THREAD

**Issue by mjbright** [takluyver/bash_kernel#34]
OK, just throwing this out there ... the problem is that there isn't the pexpect module for Windows.
(Actually the bash_kernel installs, appears in the menu but doesn't/can't work.  The failed install should be detected).

Any chance of a pexpect-less version of bash_kernel?

**Comment by takluyver** [comment]
Pexpect 4 will be importable on Windows, but we use a pty to communicate with bash, and Windows doesn't have ptys. You might be able to hack something round that, but it's likely to be buggy in ways that can't really be fixed. So at present, I don't see this happening, sorry.

**Comment by mjbright** [comment]
Had to try ... don't ask you don't get ;-)

**Comment by goyalyashpal** [comment]
> Windows doesn't have ptys

windows has `pty` for quite some time now i think

[pseudo-console-support]: https://wezfurlong.org/wezterm/install/windows.html#installing-on-windows "Pseudo Console support: Winver >= 10.0.17763"

> WezTerm requires Pseudo Console support that was first released in Windows 10.0.17763.
> \- _[pseudo-console-support] | wezterm install on windows_

[conpty]: https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/ "Windows Command-Line: Introducing the Windows Pseudo Console (ConPTY)"
[pty]: https://en.wikipedia.org/wiki/Pseudoterminal

> In the *NIX world, this isn’t a problem because *NIX provides a [“Pseudo Terminal” (PTY)][pty] infrastructure which makes it easy to build the communication plumbing for a Console or service, but Windows [did] not ... **_until now!_**
> \- _[introducing conpty][conpty] | microsoft devlog_

**Comment by goyalyashpal** [comment]
also see: https://github.com/takluyver/bash_kernel/issues/96
