### ISSUE TITLE
doesn't seem to generate incremental output

### ISSUE THREAD

**Issue by tmbdev** [takluyver/bash_kernel#36]
When running a long-running process that produces lots of output over time, it would be nice to see lines appear as they are generated. (That would seem to be a major reason for using pexpect, wouldn't it?)

However, when I use the bash_kernel, it only seems to display output from the shell when the subcommand completes.

Is this the way bash_kernel is supposed to behave?

**Comment by takluyver** [comment]
For now, yes, that's the way it's supposed to work. We use a blocking Pexpect API called [replwrap](http://pexpect.readthedocs.org/en/latest/api/replwrap.html).

**Comment by takluyver** [comment]
(Which is not to rule out changing it in the future, but it's not high priority)

**Comment by fiedl** [comment]
+1

Any progress on that? :smile: 

This could be the missing puzzle piece to my new general workflow.

**Comment by triggers** [comment]
We needed incremental output for a Jupyter project here and came up
with a solution that seems to work OK.  Please check out this pull
request: https://github.com/takluyver/bash_kernel/pull/46

**Comment by rgbkrk** [comment]
Running into this as well, wishing that I could see progress for installs or generally streaming through grep.

**Comment by takluyver** [comment]
Fixed in #46.

**Comment by takluyver** [comment]
[Tada](https://pypi.python.org/pypi/bash_kernel/0.5)! If stuff breaks, you know what to do (open an issue).
