### ISSUE TITLE
kernel dies and restart (conda)

### ISSUE THREAD

**Issue by epifanio** [takluyver/bash_kernel#41]
I'm tring to use the bash kernel on a docker container. I got this log from the shell tring to run a bash kernel:

https://gist.github.com/cbd65be613571d067d2e

Any clue on what can be wrong?

**Comment by takluyver** [comment]
It's failing to find the original prompt in bash for some reason. Do you have Pexpect 4? It should be getting reset by [this file](https://github.com/pexpect/pexpect/blob/master/pexpect/bashrc.sh).

**Comment by epifanio** [comment]
Upgrading Pexpect fixed the problem, thanks!

**Comment by takluyver** [comment]
:-)
