### ISSUE TITLE
Can't install dev version

### ISSUE THREAD

**Issue by ellisonbg** [takluyver/bash_kernel#42]
Right now there are fixes in master of bash_kernel that I need. But, because:

1. There is no setup.py in the repo.
2. A release hasn't been made since August.

I am unable to install this using pip and github URLs. I am automating a JupyterHub deployment using ansible and not being able to install with pip directly from GitHub gets to be really painful.

I am all for using things like flit to ease development and maintenance, but not being able to install from source with pip is a huge annoyance. Options:

* Release more often (even minor versions).
* Use flit to autogenerate a setup.py that is checked into the repo.

Thoughts?

**Comment by takluyver** [comment]
A new release is now up.

I don't want to resort to checking in a 'shim' setup.py, because it will lead to confusion about what's going on. Nathaniel made a proposal that would have made pip adapt to different build systems, so you would have been able to pip install from a Github URL without it needing to have a setup.py file. But the Python packaging folks didn't go for it. I'm still working out what else might be done to make it easier.

**Comment by ellisonbg** [comment]
Thanks for the release! I am interested to see where this goes...

On Mon, Nov 30, 2015 at 2:33 AM, Thomas Kluyver <notifications@github.com>
wrote:

> A new release is now up.
>
> I don't want to resort to checking in a 'shim' setup.py, because it will
> lead to confusion about what's going on. Nathaniel made a proposal that
> would have made pip adapt to different build systems, so you would have
> been able to pip install from a Github URL without it needing to have a
> setup.py file. But the Python packaging folks didn't go for it. I'm still
> working out what else might be done to make it easier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/takluyver/bash_kernel/issues/42#issuecomment-160590780>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by eburgueno** [comment]
Hi, we are running with the same issue now (we basically need the `--prefix` option to be supported). Any chance you can update the pip package again? or describe how to install from GitHub somehow?

Thanks
