### ISSUE TITLE
Some basic magics are needed

### ISSUE THREAD

**Issue by mjbright** [takluyver/bash_kernel#43]
I plan to use Jupyter + bash_kernel for tutorials, I find it extremely useful to build up a narrative with command-line operations like that.

It's unfortunate that no cell magics are available.

In particular, I'd like to find a way of initializing a file in a code cell which looks natural to a reader
(so although it's executeable code, it looks natural as if I'd just shown the contents in a Markdown cell).

For now I do a HERE document, as below, but this looks rather clunky and could confuse people.

```
cat > textfile <<EOF
line1
line2
EOF
```
A better way would be to have a %writefile/%readfile magic as IPython has, so I could have a Code cell like

```
%writefile textfile
line1
line2
```

Unless you have a better suggestion ...

A slightly nicer way

**Comment by takluyver** [comment]
I don't have any particular plan to implement magics in bash_kernel - the original idea of magics was to provide a shell-like syntax for quick interactive use in Python. So it seems rather redundant to provide a shell-like syntax in bash. ;-)

You can define your own `writefile` command that does the equivalent of `cat > textfile <<EOF` - though I don't think there's any way to get around the need for an end marker.

**Comment by sqqqrly** [comment]
I would like to ask for magics to.  My use case is a mix of python and bash.  In particular, I would like to display a simple image but gitlab (and I believe github) markdowns refuse to display images.

This works though:

**Comment by takluyver** [comment]
`display images/logo.png` should work in the bash kernel.
