### ISSUE TITLE
Where to put .bashrc?

### ISSUE THREAD

**Issue by Honestpuck** [takluyver/bash_kernel#51]
I have a .bashrc file in my home directory  but it appears that it is not being read.

Where do I need to put it?

Running latest version on OS X.

**Comment by takluyver** [comment]
It should be - here's the custom bashrc file in pexpect that sources ~/.bashrc:

https://github.com/pexpect/pexpect/blob/master/pexpect/bashrc.sh

**Comment by Honestpuck** [comment]
Thomas,

After further checking I confirmed that it is loading ~/.bashrc but that it isn't setting aliases or defining bash functions (which is almost all I have in mine). Is this a known behaviour?

**Comment by takluyver** [comment]
That's not a known behaviour, and I don't have any idea what would cause it.

**Comment by Honestpuck** [comment]
So it should work? OK. I will keep on investigating.

**Comment by Honestpuck** [comment]
Upgrading to pexpect 4.2.0 fixed the problem.

**Comment by takluyver** [comment]
Great.
