### ISSUE TITLE
%%HTML magic doesn't work under bash kernel

### ISSUE THREAD

**Issue by mojones** [takluyver/bash_kernel#52]
Not sure if this is a bug or not, seeking clarification. Under Python notebooks, we can put arbitrary HTML in a cell with the `%%HTML` magic:

```
%%HTML
<style>
div {
    background-color: red;
}
</style>
```

which I normally use for styling notebooks for giving talks. This doesn't work under the bash kernel. Do any of the jupyter magics work with this kernel? Should they? and if not, is there some other way to go about styling the notebook? I've played around with various `custom.css` files in different locations but can't get anything to work.

**Comment by takluyver** [comment]
No, bash_kernel does not support magics (in a Python notebook, magics are an *IPython* kernel feature, not a *Jupyter* feature). We could look at supporting a feature to send HTML output from bash_kernel, but it would have a somewhat different syntax.

The correct place for custom.css should be `~/.jupyter/custom/custom.css`

**Comment by mojones** [comment]
Many thanks for such a quick reply, and for clarifying the role of magics. I'll try my luck with the custom folder.
