### ISSUE TITLE
weird outputs from repeatedly calling `env`

### ISSUE THREAD

**Issue by ttimbers** [takluyver/bash_kernel#55]
When I use the command `env` to look at what environment variables exist, I get 1 of 3 answers, depending on how many times I run the `env` command... The first time I get a reasonable output, the second time I get a value of `0`, and the third time I get yet a different output. Any idea why this happens? Looks like a bug to me... I have pasted the code and output below:

```
env

TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/ct/x1hy892j365bfhpjfrm265qm0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.hTRcxjkG4D/Render
PERL5LIB=/usr/local/lib/perl5/site_perl:
TERM_PROGRAM_VERSION=343.7
TERM_SESSION_ID=C73FB697-9099-450E-B537-2786A7CD2543
USER=tiffanytimbers
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.vJ6R1ZtODG/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
JPY_PARENT_PID=7620
PAGER=cat
PATH=//anaconda/bin:/opt/local/bin:/opt/local/sbin:/Users/tiffanytimbers/Documents/Post-Doc/GWAS/vcftools_0.1.12b/perl:/usr/local/Cellar/vcftools/0.1.12b-2/bin:/Users/tiffanytimbers/bin/plink_mac:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin
PWD=/Users/tiffanytimbers/Documents/MDS-UBC/DSCI_521_platforms-dsci/lectures
LANG=en_CA.UTF-8
XPC_FLAGS=0x0
PS1=
```
```
env

0
```

```
env

XPC_SERVICE_NAME=0
HOME=/Users/tiffanytimbers
SHLVL=2
LOGNAME=tiffanytimbers
DISPLAY=/private/tmp/com.apple.launchd.U7ULVI89iY/org.macosforge.xquartz:0
_=/usr/bin/env
```

**Comment by takluyver** [comment]
Because it's looking for a special prompt sequence to mark the end of output, and that prompt is set by the environment variable `PS1`, it sees the end of the output in the middle of the real output. I have found a way around this (pexpect/pexpect#362), but we haven't done a release of Pexpect since merging it last month. If you install Pexpect from master, it should work, and I'll try to get a new release out soon.

**Comment by ttimbers** [comment]
Fantastic! Installing `Pexpect` from `master` fixes many problems I have been having with `bash_kernel`, thanks so much!

**Comment by takluyver** [comment]
Pexpect 4.2.1 is out now.
