### ISSUE TITLE
kernel hangs when output has invalid unicode

### ISSUE THREAD

**Issue by DrXyzzy** [takluyver/bash_kernel#61]
This is of interest because badly-behaved applications can create files with invalid names.

Try the following python script to create 1 good file and 2 files with bad unicode name in folder "BAD":
```
fnlist = [
    "BAD/good.txt",
    "BAD/" + "\xe1",
    "BAD/" + "\xfe\xfe\xff\xff"
]

for i,fn in enumerate(fnlist):
    with open(fn,"w") as outf:
        outf.write("Hello {}\n".format(i))
```

Then open a jupyter client with bash_kernel and the following will cause the client to stall waiting on output from the kernel:
```
echo BAD/*
```

**Comment by takluyver** [comment]
Thanks - a quick change was enough to fix this for me.
