### ISSUE TITLE
Unknown message type displayed when using the bask kernel

### ISSUE THREAD

**Issue by ssc806** [takluyver/bash_kernel#64]
OS: Mac OS 10.12.6
jupyter notebook : 5.0.0
bask kernel : latest
browser: Version 59.0.3071.115 

Whenever I switched to used the bash kernel, the notebook screen will display the following message, may be we need to know what is the unknown message here.

>[I 13:18:57.811 NotebookApp] Serving notebooks from local directory: /Users/sshao
>[I 13:18:57.811 NotebookApp] 0 active kernels 
>[I 13:18:57.811 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=a8232261512b2b7d28e14431035ef212e5ca17a6bf5fa34c
>[I 13:18:57.811 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:18:57.814 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=a8232261512b2b7d28e14431035ef212e5ca17a6bf5fa34c
>[I 13:18:58.219 NotebookApp] Accepting one-time-token-authenticated connection from ::1
>[I 13:19:10.623 NotebookApp] Kernel started: 8bc0f5f1-4593-4ec7-b5d6-9b783112da99
>[IPKernelApp] WARNING | Unknown message type: 'comm_open'
>[IPKernelApp] WARNING | Unknown message type: 'comm_open'

**Comment by takluyver** [comment]
I think it's something related to the widgets that sends a probe message. There's no need to worry about it, as far as I know.
