### ISSUE TITLE
Kernel is installing into user location when run as root

### ISSUE THREAD

**Issue by dacort** [takluyver/bash_kernel#66]
Hello 👋 

I think #65 introduced an issue where the kernel always installs into the users home directory, even when running as root or providing the `--prefix` argument. 

I'm not too familiar with argparse, but it looks like the `actions` line is setting the user flag to True, even if `_is_root` returns True.

Reproduce:
- Run `sudo python3 -m bash_kernel.install` or `sudo python3 -m bash_kernel.install --prefix /usr/local`

Expected:
- Kernel installed to `/usr/local/share/jupyter/kernels/`

Actual
- Kernel installed to `/root/.local/share/jupyter/kernels/`

**Comment by takluyver** [comment]
Thanks, good catch. The latest commit should fix it.
