### ISSUE TITLE
install permission in raspberry pi

### ISSUE THREAD

**Issue by odameron** [takluyver/bash_kernel#67]
Hello,
   I succesfully managed to install bash_kernel on a raspberry pi (raspbian stretch 2017-08-16) but I had to modify the commands in the main web page to use 'pip3' and 'python3'

The last command complained about write permission on /usr/local/share/jupyter so I had to create the directory and give permission to the user (probably not the best idea).  Do you have a better alternative?

I did:

- `pip3 install bash_kernel`
- `sudo mkdir /usr/local/share/jupyter`
- `sudo chown ${USER} /usr/local/share/jupyter`
- `python3 -m bash_kernel.install`

**Comment by takluyver** [comment]
Yup, add `--user` to the command to do a user installation (in `~/.local/share/jupyter`).

**Comment by odameron** [comment]
Great, thanks (and also, many thanks for bash_kernel)!

So eventually I did:

- `pip3 install --user bash_kernel`
- `python3 -m bash_kernel.install --user`

Do you want me to update README.rst

**Comment by takluyver** [comment]
There's actually a fix in master to make `--user` the default (when it's not run as root). I just need to do a new release. So thanks, but no need to change the README. :-)
