### ISSUE TITLE
Kernel not working with Jupyter 4.4 and Python 3.6

### ISSUE THREAD

**Issue by Naereen** [takluyver/bash_kernel#70]
I installed a fresh copy of the bash kernel, and it fails with the following exception:
```bash
[I 15:11:00.455 NotebookApp] Kernel started: 79d44efe-a83a-4da9-a6b2-c23dba9af3f5
[W 15:11:12.141 NotebookApp] Timeout waiting for kernel_info reply from 79d44efe-a83a-4da9-a6b2-c23dba9af3f5
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pexpect/expect.py", line 98, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/local/lib/python3.6/dist-packages/pexpect/pty_spawn.py", line 466, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded. 
```

Thanks in advance if you can try to solve this. I can help by providing error messages if needed.

**Comment by takluyver** [comment]
Have you customised bash to modify the prompt at all? `bash_kernel` tries to override that when it starts bash by using [this file](https://github.com/pexpect/pexpect/blob/master/pexpect/bashrc.sh), but it might be missing something.

**Comment by Naereen** [comment]
Yes, my `.bashrc` changes my PS1 and PS2.
But it seems to be a bug from `pexpect` (or `bash_kernel`?), as there is no reason to fail if the user changes his/her prompt (the file you mention should override it without any trouble)...

I tried again disabled my PS1/PS2 customization (removed my `.bashrc`), and the bug... is still exactly the same.

**Comment by takluyver** [comment]
Strange. I'm not sure what to try. I'm also not sure why it's only showing that short traceback - there should be more frames above it to show what code is being called.

Can you try running this Python code:

```python
from pexpect import replwrap
shell = replwrap.bash()
shell.run_command("echo $HOME")
```

[replwrap docs](http://pexpect.readthedocs.io/en/stable/api/replwrap.html#pexpect.replwrap.bash)

**Comment by Naereen** [comment]
OK, this works when I change a little bit my PS1/PS2 configuration.

The issue is actually not coming from "weird" PS1/PS2 (I have non-standard UTF-8 caracters in my prompt, like 
```
⏰ 23:08:34 👤 lilian @ 💻 jarvis #1 [ ~ ] ✔ 
➤➤➤ 
``` but they don't cause the issue)

Apparently, pexpect don't like bash sessions with PROMPT_COMMAND set to non-trivial functions, like [this one](https://bitbucket.org/lbesson/bin/src/master/.bashrc?fileviewer=file-view-default#.bashrc-277)

**Comment by Naereen** [comment]
It's a fun bug, but it's definetly not from `bash_kernel` so I will stop bothering you, thanks and :clap: for answering so quickly @takluyver.
I will try to obtain the same behavior without no `pexpect` failures, and if I can't find how, I will continue this bug directly on `pexpect`'s GitHub issues.

**Comment by takluyver** [comment]
Ah, your PROMPT_COMMAND modifies PS1. Yup, that would break it. Probably pexpect should unset PROMPT_COMMAND as well to avoid things like that.

I'm also one of the maintainers of pexpect, so you might find you speak to me again. ;-)

**Comment by Naereen** [comment]
OK I fixed it by using a simpler PROMPT_COMMAND that didn't use any old variable (I was using PS1OLD).
Thanks.
(https://bitbucket.org/lbesson/bin/commits/3013cb2)

**Comment by takluyver** [comment]
Thanks. I'll try to improve Pexpect as well to unset PROMPT_COMMAND

**Comment by takluyver** [comment]
https://github.com/pexpect/pexpect/pull/459

**Comment by Naereen** [comment]
Awesome, thanks for reacting to this feedback so actively! :clap:
