### ISSUE TITLE
Can't work with requests for input in general?

### ISSUE THREAD

**Issue by choldgraf** [takluyver/bash_kernel#72]
I ran into this issue when I needed `sudo` privileges within the kernel. It sounds like this is just a fundamental limitation of the jupyter server? Just wanted to make sure that's the case :-)

**Comment by takluyver** [comment]
Yup, it's a general limitation. Jupyter needs something to request a line of input, whereas programs written for the terminal just try to read from stdin. I don't know of any programmatic way to tell that the foreground program in the terminal is waiting for input.

**Comment by choldgraf** [comment]
Thanks for clarifying! FWIW I discovered this when trying to use the bash kernel in jupyterlab...opened https://github.com/jupyterlab/jupyterlab/issues/3948 to see if there's a way to just send commands directly to their terminal. Gonna close this now!
