### ISSUE TITLE
stdout streamed only line by line

### ISSUE THREAD

**Issue by yuvipanda** [takluyver/bash_kernel#74]
If I have the following code:

```bash
while true; do echo -n "."; sleep 1; done
```

I never actually see the output.

If I remove the `-n` to echo, making the code print with newlines, I do see output:

```bash
while true; do echo "."; sleep 1; done
```

Should ideally stream output as it happens, rather than waiting for newline

**Comment by kdm9** [comment]
I agree in theory, however it ends up being prohibitively inefficient as there is significant overhead on both the jupyter kernel/server and the client if you immediately push every character to the client. If you do something sensible like batching into 1kb chunks, then your example above would only update every 1000 dots in any case, which kinda makes the functionality pointless in most cases.

I'd also note that we return the output on either `'\r'` or `'\n'`, so if you e.g. have a single progress line that gets overwritten with `\r` it should work fine.
