### ISSUE TITLE
Provide better bash autocomplete

### ISSUE THREAD

**Issue by yuvipanda** [takluyver/bash_kernel#75]
Currently, the bash kernel only autocompletes variables and builtins / commands. Would be great if it could use bash / readline's completion features to autocomplete in all the ways bash itself does. https://brbsix.github.io/2015/11/29/accessing-tab-completion-programmatically-in-bash/ has a good example...

**Comment by kdm9** [comment]
hopefully solved in #126, please reopen if there are further issues
