### ISSUE TITLE
How to use with remote_ipython

### ISSUE THREAD

**Issue by noma** [takluyver/bash_kernel#79]
The kernel works well for me locally, so thanks for writing it.

However, I have trouble getting it running remotely via: [remote_ikernel](https://pypi.org/project/remote_ikernel/). It is unclear to me what the kernel command would be, or whether there is an equivalent to `[...]/bin/ipython` provided as used in this example:

```bash
remote_ikernel manage --add \
   --kernel_cmd="ipython kernel -f {connection_file}" \
   --name="Python 2.7" --cpus=2 --pe=smp --interface=sge
```

Any ideas?

**Comment by takluyver** [comment]
The equivalent of the `ipython kernel` command looks like `.../bin/python -m bash_kernel` - see here for where it's generated:

https://github.com/takluyver/bash_kernel/blob/0966dc102d7549f5c909c93de633a95b2af9f707/bash_kernel/install.py#L9
