### ISSUE TITLE
Can not open editor through notebook

### ISSUE THREAD

**Issue by SeuperHakkerJa** [takluyver/bash_kernel#81]
In the jupyter notebook, if open text file through editors like vim or emacs, the notebook seems to be stuck. ps. when using command like:
`vim sample.txt`
it just simply stuck and no further input is processed.

**Comment by takluyver** [comment]
Yup, that's what will happen. It runs bash in a virtual terminal, looking for a special input prompt to show when it's done executing some code. When you start an editor, or some other program that takes over the terminal, it can't process that, and it never sees the prompt for the next input, so it gets stuck.
