### ISSUE TITLE
Kernel doesn't intepret the correct virtualenv

### ISSUE THREAD

**Issue by queueburt** [takluyver/bash_kernel#82]
When executing python code via bash in bash_kernel, execution defaults to global system version of python and its respective packages despite the fact that jupyter is running inside a pyenv virtualenv.  Usage of standard Python 3 kernel and the %%bash magic behaves correctly and executes code within the context of the virtualenv.  Current version of jupyter-core is 4.4.0, bash_kernel is 0.7.1, pyenv is 1.2.9, and OS is Ubuntu 18.04.  This is isolated to this specific version and OS, as the same configuration is on a Macbook Pro and functions as expected.

**Comment by takluyver** [comment]
What does `which python` show? `bash_kernel` isn't doing anything special for running Python code, it will use whatever python executable is found on `$PATH`, just like bash normally does.

It may depend whether you 'activate' the environment first, or launch Jupyter without activating the environment (by running a path, or by symlinking the `jupyter` script to another directory). Activating the environment adds it to $PATH.

**Comment by queueburt** [comment]
Pyenv works a little bit differently than traditional virtualenv.  Pyenv is effectively global and uses shims in its config directory to proxy python requests to the appropriate versions.  So `which python` universally returns a result of `home/<USER>/.pyenv/shims/python` no matter what environment is active.  I can tell it's using the wrong version, however, by the results of `pip list` and `pip version`, as well as the fact that the exact same command that returns `Module not found` in Jupyter works correctly when executed directly from bash in the virtualenv.  I realize there's a chance this is a pyenv issue, but I list it here specifically due to the fact that it's worked correctly in the past on different platforms, and my Pyenv versions are the same on each.

**Comment by takluyver** [comment]
Pyenv has a description here of how its shims choose which Python to run:

https://github.com/pyenv/pyenv#choosing-the-python-version

Can you follow through that and figure out what it's doing in your system?

**Comment by queueburt** [comment]
On further investigation, this seems to be an issue with the way my IDE activates virtualenvs.  For some wacky reason it can determine what virtualenv it's in and execute code properly, but it doesn't pass through the environment variables Bash needs to do the same.  Thanks for the quick feedback, I'm closing this now and trying to chase the problem down in the IDE.

**Comment by takluyver** [comment]
Fair enough. Feel free to drop any links or info here about what you find with your IDE; it's possible it will one day help someone else with a similar issue.

**Comment by queueburt** [comment]
A few days and some substantial bugchasing later, I have a resolution to this problem.  Turns out that the issue wasn't with the way the IDE activated virtualenvs per se (though it doesn't do it as effectively as it should), it had to do with differences in shell integration between platforms (OS X vs. Ubuntu 18.04 in this case).  Ubuntu recommends activating Pyenv shims in .bashrc as opposed to .bash_profile in OS X.  This effectively means that a new Ubuntu Bash session (including bash_kernel) will re-execute `pyenv init` every time, even when *in* a virtualenv.  This unintentionally rewrites $PATH back to the global defaults, thus eradicating the virtualenv's binaries.  This isn't typically a problem since you usually leverage a virtualenv inside a single session, but bash_kernel is one of the rare instances where we need to maintain our $PATH.

Pyenv recommends the following .bashrc modification to enable shell integration:

`if command -v pyenv 1>/dev/null 2>&1; then`
`eval "$(pyenv init -)"`
`eval "$(pyenv virtualenv-init -)"`
`fi`

Fortunately, pyenv sets the $VIRTUAL_ENV environment when it activates a virtualenv, so a simple modification to that .bashrc code lets us avoid the accidental $PATH overwriting.  Fix below:

`if command -v pyenv 1>/dev/null 2>&1 && [ -z "$VIRTUAL_ENV" ]; then`
`eval "$(pyenv init -)"`
`eval "$(pyenv virtualenv-init -)"`
`fi`

**Comment by takluyver** [comment]
Thanks for the follow-up!

As I understand it, there's no change to be done in bash_kernel, correct?

**Comment by queueburt** [comment]
Yes, that's correct.  In fact, I'd probably argue that any change correcting this in bash_kernel would probably be fundamentally at odds with what makes this so awesome in the first place.  :-)  Thanks for being so responsive, though!

**Comment by takluyver** [comment]
Great, I love it when I don't need to do anything! :stuck_out_tongue:
