### ISSUE TITLE
Can't use sudo

### ISSUE THREAD

**Issue by thwee-alchemist** [takluyver/bash_kernel#83]
I really love the concept of this. I see how productivity would improve by being able to document shell scripts, and tinker with them at the same time. However, I noticed that sudo won't work because it requires special input, I guess.

**Comment by takluyver** [comment]
Yup, in general commands that require input don't work. There's a mismatch between the way Jupyter 'thinks about' input (something has to ask for a line of input), and the way terminals do it (you can send input at any time, and it's up to a program when it reads it).

Someone just suggested a possible idea to bridge those two models; it's not clear yet how practical it is: https://github.com/pexpect/pexpect/issues/557

**Comment by thwee-alchemist** [comment]
Do you know if it's possible to set the bash to run as a certain user, and just give that user non-password access? I'm doing some system maintenance, and was hoping to document my adventures in a notebook.

**Comment by takluyver** [comment]
You could run the entire notebook server as a particular user (we don't recommend running it as root, but it's possible if you want to take that risk). Other than that, you'd have to hack bash_kernel to start bash as a different user. Here's where it launches bash:

https://github.com/takluyver/bash_kernel/blob/0966dc102d7549f5c909c93de633a95b2af9f707/bash_kernel/kernel.py#L94-L96

**Comment by thwee-alchemist** [comment]
This would be really useful for installations, just download the notebook and run the commands, documentation included. If only sudo worked.
