### ISSUE TITLE
Using with Python 3.7

### ISSUE THREAD

**Issue by thestumbler** [takluyver/bash_kernel#86]
Just an observation - I was running Jupyter Lab and had the bash kernel installed under Python 3.6, no issues. For some reason in the last week, my system upgraded to Python 3.7, and the bash kernel quit working.  It gave an error that it couldn't open file `/usr/local/opt/python/bin/python3.6`.  Which made sense, that file was no longer there.  I tried reinstalling Jupyter Notebook, Jupyter Lab, Python, and bash_kernel without success.  I started poking around in the configuration files and found the bash kernel.json file, which had the offending file.  Manually edited the .json file, changing `...python3.6` to `...python3.7`, and it works fine now.

```python
{
    "argv": ["/usr/local/opt/python/bin/python3.7", "-m", "bash_kernel", "-f", "{connection_file}"],  
    "codemirror_mode": "shell",
    "display_name": "Bash",
    "env": {"PS1": "$"}, 
    "language": "bash"
}
```

**Comment by takluyver** [comment]
Yep, the kernelspec file contains the full path to the Python interpreter. If that changes, then you have to change or recreate the kernelspec, which you can do by re-running `python -m bash_kernel.install`.
