### ISSUE TITLE
add an icon for use in jupyterlab?

### ISSUE THREAD

**Issue by vnijs** [takluyver/bash_kernel#88]
Is it possible to add an icon of some sort for bash? Currently it looks a but ... bland :) I looked through the code but it wasn't clear to me where this might be added.

![image](https://user-images.githubusercontent.com/2998956/56621131-2a673f80-65e0-11e9-90d3-9a8ff8558001.png)

Perhaps one of these would work?

[bash icon](https://www.google.com/search?tbm=isch&q=bash+icon&chips=q:bash+icon,g_1:transparent:CciUze6S_vo%3D&usg=AI4_-kTNoFom3-AL5eDafbNk0sQFY6xxOg&sa=X&ved=0ahUKEwiT97yap-fhAhXErZ4KHfkIATUQ4lYILigD&biw=2048&bih=979&dpr=1.25)

**Comment by kdm9** [comment]
closed in #134
