### ISSUE TITLE
Edit a file in the JupyterLab editor

### ISSUE THREAD

**Issue by mardukbp** [takluyver/bash_kernel#93]
This would be very useful. How can it be implemented?

**Comment by mardukbp** [comment]
I will ask in the JupyterLab Discourse, whether there is an API to call the editor.

**Comment by kdm9** [comment]
I'm not sure if any mechanism for doing this exists, and if it did, would be a juptyer/juptyerlab/jupyterhub feature. Please reopen if you find such a mechanism and would like any code added to bash_kernel to support it.
