### ISSUE TITLE
conda-forge recipe for bash_kernel

### ISSUE THREAD

**Issue by BoPeng** [takluyver/bash_kernel#94]
@takluyver 

I have just created a [conda-forge recipe](https://github.com/conda-forge/staged-recipes/pull/9348) for `bash_kernel`  because I need `bash_kernel` to add my package [sos-bash](https://github.com/vatlab/sos-bash) to conda-forge. Please let me know if you are ok with it, and if yes, if you would like to maintain it in the future (I can remove myself from the maintainers list if you prefer).

**Comment by blink1073** [comment]
Thanks @BoPeng!  @takluyver, I can be a maintainer as well if you like.

**Comment by BoPeng** [comment]
It took me a while to get the recipe work but all tests pass now. I have just added  @blink1073 to the maintainers list and we will need approval from @takluyver to get it merged.

@takluyver @blink1073 I think you will need to reply in the [PR](https://github.com/conda-forge/staged-recipes/pull/9348) to agree to maintain the recipe.
