### ISSUE TITLE
Can this kernel be run on Google Colab?

### ISSUE THREAD

**Issue by nikochiko** [takluyver/bash_kernel#99]
Hello there! I would like to use this bash kernel with Google Colab notebooks. Any way to configure that?

**Comment by kdm9** [comment]
Sorry this has gone unanswered for so long. I have no idea as I don't use google colab, but so long as you can install a python package (bash_kernel) and run bash, then there should be nothing stopping bash_kernel working.

If it doesn't work, I'd consider it a bug in bash_kernel, so please try it out and reopen/make a new issue if something goes wrong
